repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-yaml
        args: ['--allow-multiple-documents']
        exclude: '^jenkins/jjb-.*$'
      - id: end-of-file-fixer
      - id: trailing-whitespace
      #  - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=512"]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
  #  - id: fix-encoding-pragma
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
#  - repo: https://github.com/jumanjihouse/pre-commit-hooks
#    rev: 2.1.3
#    hooks:
#      - id: shellcheck
