[tool.poetry]
name = "jenkins-job-manager"
version = "0.1.3"
description = ""
authors = ["Jeremy Lavergne <github@lavergne.me>", "Jon Wedaman <jweede@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
jenkins-job-builder = "^3.5.0"
jinja2 = "^2.11.2"
python-jenkins = "^1.7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
jjm = 'jenkins_job_manager.cli:jjm'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

